rss_list = [
["G1", "brasil", "http://g1.globo.com/dynamo/brasil/rss2.xml"],
["G1", "carros", "http://g1.globo.com/dynamo/carros/rss2.xml"],
["G1", "ciencia e saude", "http://g1.globo.com/dynamo/ciencia-e-saude/rss2.xml"],
["G1", "carreira", "http://g1.globo.com/dynamo/concursos-e-emprego/rss2.xml"],
["G1", "economia", "http://g1.globo.com/dynamo/economia/rss2.xml"],
["G1", "educacao", "http://g1.globo.com/dynamo/educacao/rss2.xml"],
["G1", "loterias", "http://g1.globo.com/dynamo/loterias/rss2.xml"],
["G1", "mundo", "http://g1.globo.com/dynamo/mundo/rss2.xml"],
["G1", "musica", "http://g1.globo.com/dynamo/musica/rss2.xml"],
["G1", "natureza", "http://g1.globo.com/dynamo/natureza/rss2.xml"],
["G1", "politica", "http://g1.globo.com/dynamo/politica/mensalao/rss2.xml"],
["G1", "arte", "http://g1.globo.com/dynamo/pop-arte/rss2.xml"],
["G1", "tecnologia e  games", "http://g1.globo.com/dynamo/tecnologia/rss2.xml"],
["G1", "turismo", "http://g1.globo.com/dynamo/turismo-e-viagem/rss2.xml"],
["Folha", "tecnologia", "https://feeds.folha.uol.com.br/tec/rss091.xml"],
["Folha", "turismo", "https://feeds.folha.uol.com.br/turismo/rss091.xml"],
["Folha", "comida", "https://feeds.folha.uol.com.br/comida/rss091.xml"],
["Folha", "educacao", "https://feeds.folha.uol.com.br/educacao/rss091.xml"],
["Folha", "ciencia", "https://feeds.folha.uol.com.br/ciencia/rss091.xml"],
["Folha", "mundo", "https://feeds.folha.uol.com.br/mundo/rss091.xml"],
["Folha", "esporte", "https://feeds.folha.uol.com.br/esporte/rss091.xml"],
["Folha", "natureza", "https://feeds.folha.uol.com.br/ambiente/rss091.xml"],
["Valor", "brasil", "https://www.valor.com.br/brasil/rss"],
["Valor", "politica", "https://www.valor.com.br/politica/rss"],
["Valor", "economia", "https://www.valor.com.br/financas/rss"],
["Valor", "empresas", "https://www.valor.com.br/empresas/rss"],
["Valor", "agro", "https://www.valor.com.br/agro/rss"],
["Valor", "mundo", "https://www.valor.com.br/internacional/rss"],
["Valor", "carreira", "https://www.valor.com.br/carreira/rss"],
["R7", "carreira", "http://noticias.r7.com/carreiras/feed.xml"],
["R7", "economia", "http://noticias.r7.com/economia/feed.xml"],
["R7", "saude", "http://noticias.r7.com/saude/feed.xml"],
["R7", "brasil", "http://noticias.r7.com/brasil/feed.xml"],
["R7", "mundo", "http://noticias.r7.com/internacional/feed.xml"],
["R7", "tecnologia e ciencia", "http://noticias.r7.com/tecnologia-e-ciencia/feed.xml"],
["R7", "moda", "http://meuestilo.r7.com/moda/feed.xml"],
["R7", "esporte", "http://esportes.r7.com/feed.xml"],
["UOL", "tecnologia", "http://tecnologia.uol.com.br/ultnot/index.xml"],
["UOL", "esporte", "http://esporte.uol.com.br/basquete/ultimas/index.xml"],
["UOL", "musica", "http://musica.uol.com.br/ultnot/index.xml"],
["UOL", "cinema", "http://cinema.uol.com.br/ultnot/index.xml"],
["BBC", "brasil", "http://www.bbc.co.uk/portuguese/topicos/brasil/index.xml"],
["EBC", "tecnologia", "http://www.ebc.com.br/rss/tecnologia/feed.xml"],
["EBC", "esporte", "http://www.ebc.com.br/rss/esportes/feed.xml"],
["EBC", "educacao", "http://www.ebc.com.br/rss/educacao/feed.xml"]
]
